version: '2.7'
http:
    address: 0.0.0.0:80
    pool:
        num_workers: 0
        max_jobs: 500
        supervisor:
            exec_ttl: 30s
    static:
        dir: "/var/www/app/public"
    middleware: [ "static" ]

server:
    command: "php ./vendor/bin/roadrunner-worker"

rpc:
    listen: tcp://0.0.0.0:6001

logs:
    mode: production
    output: stdout
    encoding: json
