version: '3'
http:
    address: 0.0.0.0:80
    pool:
        num_workers: 10
        max_jobs: 100
        supervisor:
            exec_ttl: 30s
    static:
        dir: "/app/public"
    middleware: [ "static" ]

status:
    address: 0.0.0.0:2114
    unavailable_status_code: 501

server:
    command: "php ./vendor/bin/roadrunner-worker"

rpc:
    listen: tcp://0.0.0.0:6001

logs:
    mode: production
    output: stdout
    encoding: console
